# frozen_string_literal: true

require "rails_helper"
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe V1::AppsController, type: :controller do
  fixtures :all
  # This should return the minimal set of attributes required to create a valid
  # App. As you add validations to App, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { name: "Slack" } }

  let(:invalid_attributes) { { name: nil, owner_id: 1, script: "<script>" } }

  let(:valid_content_type) { "application/json; charset=utf-8" }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AppsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:user) { create(:user) }

  before { sign_in user }

  describe "GET #index" do
    it "returns a success response" do
      create(:app, owner: user)
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      app = subject.current_user.apps.create! valid_attributes
      get :show, params: { id: app.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new App" do
        expect do
          post :create, params: { app: valid_attributes }, session: valid_session
        end.to change(App, :count).by(1)
      end

      it "renders a JSON response with the new app" do
        post :create, params: { app: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq(valid_content_type)
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new app" do

        post :create, params: { app: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq(valid_content_type)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { { name: "Tesla" } }

      it "updates the requested app" do
        app = subject.current_user.apps.create! valid_attributes
        put :update, params: { id: app.to_param, app: new_attributes }, session: valid_session
        app.reload
        expect(app.name).to eq("Tesla")
      end

      it "renders a JSON response with the app" do
        app = subject.current_user.apps.create! valid_attributes
        put :update, params: { id: app.to_param, app: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq(valid_content_type)
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the app" do
        app = subject.current_user.apps.create! valid_attributes

        put :update, params: { id: app.to_param, app: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq(valid_content_type)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested app" do
      app = subject.current_user.apps.create! valid_attributes
      expect do
        delete :destroy, params: { id: app.to_param }, session: valid_session
      end.to change(App, :count).by(-1)
    end
  end
end
